image: node:latest

before_script:
 - npm prune
 - npm install -g angular-cli
 - npm install -g firebase-tools
 - npm install
 - ng build --prod

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - firebase use --token $FIREBASE_DEPLOY_KEY owlvision-be46e
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY